name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1.10.0
        with:
          node-version: '24'
          cache: true

      - name: Run linter
        run: vp check

  test:
    name: Build & Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1.10.0
        with:
          node-version: '24'
          cache: true

      - name: Install Playwright browsers
        run: vp exec playwright install --with-deps chromium

      - name: Build
        run: vp run build

      - name: Run tests
        run: vp test --coverage

      - name: Build Storybook
        if: always()
        run: vp run storybook:build

      - name: Publish and test Storybook
        if: always() && matrix.os == 'ubuntu-latest'
        uses: chromaui/action@eea1606238fd97a70b5af723d103953d1f40967b # v15.3.1
        with:
          projectToken: 'chpt_12a8831ee2a9ae4'
          # Don't wait until Chroma verified the build (for this we have the Github check)
          exitOnceUploaded: true
          storybookBuildDir: storybook-static
          debug: true

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
